### ISSUE TITLE
Reflecting updated state on putItem, batchWriteItem

### ISSUE THREAD

**Issue by rclark** [mapbox/dyno#110]
![screen shot 2015-11-13 at 2 52 19 pm](https://cloud.githubusercontent.com/assets/515424/11158564/537b667a-8a16-11e5-8ddb-d69e163d63e3.png)

Since v1 dyno inherits straight from aws-sdk, that means it also inherits this behavior, making it such that putItem requests (and those in batch) don't reflect the final state of the item. 

Do any of you see this as a problem @mick @willwhite @jakepruitt?

**Comment by willwhite** [comment]
I think this is fine. It's possible to pass in the `ReturnValues` option, right?

**Comment by rclark** [comment]
No, see the image above: you can't get anything out of `putItems` other than nothing, or the state of attributes _before_ the put.

**Comment by mick** [comment]
This seems fine, on a put if its successful you already have the value.
