### ISSUE TITLE
Working with local DynamoDB

### ISSUE THREAD

**Issue by Minstel** [mapbox/dyno#141]
Is it possible to make dyno work with local DynamoDB? I didn't find info about this. If it's not possible, it would be great to add this ability.

**Comment by mcwhittemore** [comment]
Yep. I tend to use this with [dynalite](https://github.com/mhart/dynalite#example).

Here is how you'd configure `dyno` rather than the `AWS.DynamoDB`.

```
var Dyno = require('dyno');

var dyno = Dyno({
    region: 'us-east-1',
    endpoint: 'http://localhost: 4567',
    table: 'table-name'
});
```

Please close if this worked for you.

**Comment by mcwhittemore** [comment]
Or... I can hit the wrong button and close this... :(

**Comment by Minstel** [comment]
@mcwhittemore Great thanks! I can not check it now or in nearest future, but I suppose that will work :)
