### ISSUE TITLE
Support for ConditionExpression

### ISSUE THREAD

**Issue by willwhite** [mapbox/dyno#38]
It seems like `Expected` is deprecated.

> Expected — (map<map>) There is a newer parameter available. Use ConditionExpression instead. Note that if you use Expected and ConditionExpression at the same time, DynamoDB will return a ValidationException exception.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html

And has been replaced by `ConditionExpression`:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html

**Comment by rclark** [comment]
done in #106
