### ISSUE TITLE
Mock dynamodb-stream objects in kinesis are kind of lies

### ISSUE THREAD

**Issue by rclark** [mapbox/dyno#66]
I'm realizing that we've confused a distinction between **records** in a stream and **events** that something like Lambda or an SNS would receive. What this boils down to is that it looks like we're putting a dynamodb **record**, wrapped in a dynamodb **event** into a kinesis **record**.

Then if I'm using lambda to consume the stream, I'm getting a dynamo **record** wrapped in a dynamo **event** wrapped in a kinesis **record** wrapped in a kinesis **event**. More JSON to help explain here: https://gist.github.com/rclark/a97a73a61fc124e7f78d. This highlights some of the subtle differences between dynamodb streams and kinesis streams that we can't really be aware of before being able to actually use dynamodb streams.

I think that a smarter approach for now would be to drop the dynamodb **event** wrapper. This means a test [like this one](https://github.com/mapbox/dyno/blob/bd367c2f1da9687840b2695fe39023170c19a931/test/test.kinesis.js#L115-L127) would change its assertion to:

```js
t.deepEqual(clean(found), {
    Data: JSON.stringify({
        Keys: { id: { S: 'the-id' } },
        SequenceNumber: '0',
        SizeBytes: 0,
        StreamViewType: 'KEYS_ONLY'
    }),
    PartitionKey: JSON.stringify({ id: { S: 'the-id' } })
}, 'expected updateItem params');
```

cc @mick @willwhite @freenerd

**Comment by mick** [comment]
Yeah that totally makes since. The dynamo events are rename / repurposed kinesis events. I was wrongly under the impression that it would still be a kinesis event with the dynamo event inside it.

**Comment by willwhite** [comment]
:+1: sounds good to me. Weird that these are same same but different.
