### ISSUE TITLE
Handling batch write failures

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/dyno#80]
Batch writes are performed in parallel chunks of 25, but if one chunk fails, the returned error will only contain unprocessed items from that chunk. In the meantime, if other chunks of the same batch write request fail, their unprocessed items will not be returned. 

@willwhite am I understanding that correctly?

**Comment by rclark** [comment]
So that I'm sure I understand the concern:

I `putItems` with an array of 53 items. This makes 3 DynamoDB requests. The second one fails in some blippy network fashion. We need to make sure that you learn the outcome of all three requests, and are returned any and all of the unprocessed items.

**Comment by emilymcafee** [comment]
Correct. The concern is that the 2nd _and_ 3rd requests fail, but the only error returned is from the 2nd.

queue-async only returns the first error that occurs to the `await` callback, so for requests running in parallel, even if multiple requests fail, we will only learn about the first failure and it might appear as if the others were successful.

**Comment by rclark** [comment]
I started up a branch that allows *all* the batch requests to go to completion, and aggregates the unprocessed items returned from each of them into a single error message.

Then I realized that returning unprocessed items is actually untested as-is, difficult to test, and especially difficult to test for this scenario. It'll just take a minute to come up with the right way to do this...

**Comment by rclark** [comment]
#106 basically means that the caller needs to handle failures themselves -- dyno never aggregates responses or retries unprocessed items in this brave new world.
