### ISSUE TITLE
Add batchWriteItem

### ISSUE THREAD

**Issue by willwhite** [mapbox/dyno#81]
DynamoDB has [`batchWriteItems()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#batchWriteItem-property), which allows you to put and delete records within a single request. Dyno breaks away from this pattern and instead implements two separate batch functions for putting and deleting. What's the thinking behind this change?

We should expose a function that allows users to take advantage of the combined request.

/cc @rclark

**Comment by rclark** [comment]
Done in #106
