### ISSUE TITLE
better docs

### ISSUE THREAD

**Issue by mick** [mapbox/dyno#9]
More examples for:

 - query
 - scan
 - paging
 - streaming
 - query options

**Comment by tmcw** [comment]
I'll grab this, I think doxme can knock this out pretty quickly.

**Comment by rclark** [comment]
@tmcw is this the approach you're taking? I'm noticing some errors in the comments and wondering if it would help at all if I correct things as I see them?

**Comment by tmcw** [comment]
@rclark yep! initial docs are being compiled with doxme into [API.md](https://github.com/mapbox/dyno/blob/master/API.md) but we'll switch to `documentation` once it is stable. jsdoc is the way to go.
