### ISSUE TITLE
Drop kinesis writing

### ISSUE THREAD

**Issue by rclark** [mapbox/dyno#92]
Now that DynamoDB streams are real, I'm inclined to remove the dyno code that uses kinesis as a shim. Any objections @mick or @willwhite?

**Comment by mick** [comment]
:+1: :tada:

**Comment by willwhite** [comment]
Yes! Let's deprecate it!

On Monday, July 20, 2015, Mick Thompson <notifications@github.com> wrote:

> [image: :+1:] [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/dyno/issues/92#issuecomment-123083132>.
>


-- 
202-250-3633 | will@mapbox.com | @willwhitedc

**Comment by rclark** [comment]
Done in #106
