### ISSUE TITLE
`dyno import` does not seem to work

### ISSUE THREAD

**Issue by tuscland** [mapbox/dyno#96]
Hello,

Using `dyno export` produce a file whose first line is the table definition and other lines are the contents of the table. Unfortunately dyno fails to parse the first line because it expect dynamodb types as in the following lines.

Has anyone already used `dyno import` successfully?

All the best,
Cam

**Comment by rclark** [comment]
Hi! `dyno import` ought to [use that first line to create a table](https://github.com/mapbox/dyno/blob/45b0cb341f9c75fb8602f0ab44e06ee8263e78b0/bin/cli.js#L169-L176) that matches the exported schema. Can you provide a stack trace for the error you're seeing when you tried to run the import command?

**Comment by tuscland** [comment]
Hello!

Here it is:
```
nightfly:20150915 camille$ cat dumps-production/cex_production_catalog.dump | dyno import local/cex_development_catalog

/usr/local/lib/node_modules/dyno/node_modules/dynamodb-doc/lib/datatypes.js:304
                throw "Service returned unrecognized datatype " + key;
                                                                ^
Service returned unrecognized datatype 0
````

The dump was produced with `dyno export`.

**Comment by rclark** [comment]
Been a while, but I'm going to pick this up again -- I'll write a test for round-trip export --> import and see what falls out.
